Update GenericCloner.java
The tool breaks with any argument in the profile containing escaped strings with

java.lang.IllegalArgumentException: character to be escaped is missing
        at java.util.regex.Matcher.appendReplacement(Matcher.java:809)
        at java.util.regex.Matcher.replaceAll(Matcher.java:955)
        at java.lang.String.replaceAll(String.java:2223)
        at org.jboss.tfonteyne.profilecloner.GenericCloner.escape(GenericCloner.java:360)

It's because of the used literals, but I think the core is using  replaceAll  instead of  replace and was just a typo here, because there's no needs for RegExp's.